### PR TITLE
changed convertSoupToExcellonDrillCommands to use metric units

### PR DESCRIPTION
**Pull request by ShiboSoftwareDev**
@seveibar It worked after I changed the units used in the ptr file to metric, it seems like it was receiving inches and converting them to inches again which explains the tiny drill holes.

### CODE REVIEW

**Comment by ShiboSoftwareDev** [comment]
image
However I found out that in the footprinter repo holes were being created with diameters labeled in mm which doesn't make sense imo, was that a typo or is it a misunderstanding on my part. @seveibar what do you think?

**Comment by ShiboSoftwareDev** [comment]
also format checks are still failing

**Comment by ShiboSoftwareDev** [comment]
image
this is how it looks like now

**Review by seveibar — APPROVED** [review]
Nice!

**Review by seveibar — APPROVED** [review]

**Comment by seveibar** [comment]
Yes someone has to pr the fix i described to fix the format check, is an open issue

**Comment by seveibar** [comment]
@ShiboSoftwareDev fwiw we basically want everything to be in mm at the end of the day, whenever you see a number that isnt a string it should be mm

**Pull request merged**
