### PR TITLE
added optional outline prop to board-builder

### PR DESCRIPTION
**Pull request by ShiboSoftwareDev**
I ignored the gerber generator for now to work on the pcb-viewer first. The board will be drawn with the outline option if it has at least three elements in it, is it a good idea to default it to an empty array?

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
nice, yea totally ok to skip the gerber generation

**Comment by seveibar** [comment]
@ShiboSoftwareDev i think the installation is failing, maybe because of a bun lockfile issue

**Comment by ShiboSoftwareDev** [comment]
I'm trying to fix it

**Comment by ShiboSoftwareDev** [comment]
@seveibar I'm getting too many type errors, is it bacause it is using deprecated type definitions? It was using an older version of /props and /soup

**Comment by seveibar** [comment]
@ShiboSoftwareDev yea i think you're getting hit with type errors that other people introduced, want to try to fix them? I think the changes are pretty minor, for `route_thickness_mode` it's supposed to default to `"interpolated"` but i think for some reason `z....default("interpolated")` needed to be `z....default("interpolated").optional()`, but we can patch it just by setting it explicitly in builder. Look like there are some other issues due to the upgrade that also are just small things like that :/

**Comment by ShiboSoftwareDev** [comment]
@seveibar build checks succeeded but not format checks

**Comment by seveibar** [comment]
yea the format check failure is related to https://github.com/tscircuit/plop/issues/3

we need to update formatbot.yml to not run against forks.

The prettier check failing is legit though, are you able to run prettier against those files?

Note: we don't use prettier for other repos, but this repo is really really old lol

**Comment by seveibar** [comment]
tried to fix the formatbot issue, hopefully this does it: https://github.com/tscircuit/builder/commit/581f112e85c2075beb9803100073ea9055ccea7a

**Pull request merged**
