### PR TITLE
refactor: cleanup of soup which are imported from the package

### PR DESCRIPTION
**Pull request by imrishabh18**
Soup is getting imported from the package, so this folder is not needed.

### CODE REVIEW

**Comment by seveibar** [comment]
you're a hero if you get this done. I might suggest re-exporting from `lib/soup` the exports from `@tscircuit/soup` to make the refactor easier (either way is totally good)

godspeed

**Comment by imrishabh18** [comment]
Haha, let me try that way

**Comment by imrishabh18** [comment]
@seveibar Finally!! all checks passed 🎉. This looks so satisfying to see

Screenshot 2024-07-19 at 11 47 20 PM

**Review by seveibar — APPROVED** [review]
HUGE ❤️ ❤️ ❤️ ❤️ ❤️

**Pull request merged**
