### PR TITLE
feat:  pcb snapshot added

### PR DESCRIPTION
**Pull request by imrishabh18**
Closes - https://github.com/tscircuit/tscircuit/issues/310

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
awesome, would love to see it put in a test as an example too

**Comment by imrishabh18** [comment]
Let me add and commit that.

**Comment by imrishabh18** [comment]
True, the Github diff for snapshots looks neat!

**Comment by seveibar** [comment]
@imrishabh18 looking at the dnapshot here, we might want to add a -pcb.snapshot.png or -sch.snapshot.png suffix so that prople could use both. Not a huge deal but might be nice

**Pull request merged**
