### PR TITLE
Obstacle for net lables

### PR DESCRIPTION
**Pull request by imrishabh18**
Fixes issue - https://github.com/tscircuit/tscircuit/issues/201

Screenshot 2024-06-28 at 5 14 46 PM

### CODE REVIEW

**Comment by imrishabh18** [comment]
Hey @seveibar, Please review this PR?

**Comment by imrishabh18** [comment]
I have noticed that all the net_labels with length `> 5` is having some extra padding on the right, and because of that some amount of overlap is there on the labels end.

Screenshot 2024-06-28 at 5 36 48 PM

**Review by seveibar — APPROVED** [review]
nice! I would also love to also have your test in there (although maybe put into a better directory/renamed) but it's easy enough to recreate (I don't usually merge my draft PRs when I'm demonstrating things hehe but I could in this case 😁 )

**Comment by seveibar** [comment]
@imrishabh18 some checks failing, I'll give you some access on the repo so that workflows run automatically in the future

**Comment by imrishabh18** [comment]
@seveibar Feel free to merge your PR itself, if not let me know. I will add the tests file back and then commit it

**Comment by seveibar** [comment]
@imrishabh18 ah yea sorry my convention is to approve if the code looks good even before the checks are passing. We do need to get all the checks passing before I can merge (it's failing typecheck and prettier-check)

**Comment by imrishabh18** [comment]
@seveibar Workflows are passing, and the test has been added into this.

**Review by seveibar — APPROVED** [review]

**Pull request merged**
